### ISSUE TITLE
Scheme error :  upi://pay

### ISSUE THREAD

**Issue by grit-ameen** [aslisubhash/Futter-UPI-Payment#2]
E/flutter (25671): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Illegal scheme character (at character 4)
E/flutter (25671): upi://pay
E/flutter (25671):    ^
E/flutter (25671): 
E/flutter (25671): #0      _Uri._fail (dart:core/uri.dart:1738:5)
E/flutter (25671): #1      _Uri._makeScheme (dart:core/uri.dart:2279:9)
E/flutter (25671): #2      new _Uri (dart:core/uri.dart:1648:16)
E/flutter (25671): #3      UpiPaymentHandler._createUpiUrl (package:upi_payment_flutter/src/upi_payment_handler.dart:40:12)

**Comment by muhd-ameen** [comment]
@aslisubhash could you please check above issue, i also have same issue

**Comment by Psquare-0** [comment]
paste the following below the `</application>` tag (closing tag) in your android manifest

`<queries>
      <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="upi" />
      </intent>
    </queries>`

**Comment by muhd-ameen** [comment]
let check and update, thanks for your response:)
